reveal:
  width: 1280
  height: 720
  backgroundTransition: "none"
  center: true
  controls: true
  fragmentInURL: true
  fragments: true
  hash: true
  history: false
  help: true
  hideCursorTime: 2000
  hideInactiveCursor: true
  keyboard: true
  overview: false
  progress: true
  touch: true
  vertical-slides: true
  slideNumber: true
  transition: "none"

chart:
  defaults:
    font: { size: 20 }
    color: "black"
    animation: false
    plugins:
      colorschemes:
        scheme: "tableau.Classic10"
      title:
        font: { weight: "normal", size: 30 }
      legend:
        position: "bottom"

menu:
  side: "left"
  width: "wide"
  numbers: true
  titleSelector: "h1"
  useTextContentForMissingTitles: false
  hideMissingTitles: false
  markers: false
  custom: false
  themes: false
  transitions: false
  openButton: true
  openSlideNumber: false
  keyboard: true
  sticky: false
  autoOpen: true
  delayInit: false
  openOnInit: false
  loadIcons: false

math:
  macros:
    R: '{{\mathrm{{I}\kern-.15em{R}}}}'
    laplace: '{\Delta}'
    grad: '{\nabla}'
    T: '^{\mathsf{T}}'
    abs: ['\left\lvert #1 \right\rvert', 1]
    det: ['\left\lvert #1 \right\rvert', 1]
    norm: ['\left\Vert #1 \right\Vert', 1]
    iprod: ['\left\langle #1 \right\rangle', 1]
    vec: ['{\mathbf{\boldsymbol{#1}}}', 1]
    mat: ['{\mathbf{\boldsymbol{#1}}}', 1]
    set: ['\mathcal{#1}', 1]
    func: ['\mathrm{#1}', 1]
    trans: ['{#1}\mkern-1mu^{\mathsf{T}}', 1]
    matrix: ['\begin{bmatrix} #1 \end{bmatrix}', 1]
    vector: ['\begin{pmatrix} #1 \end{pmatrix}', 1]
    of: ['\left( #1 \right\)', 1]
    diff: ['\frac{\mathrm{d}{#1}}{\mathrm{d}{#2}}', 2]
    pdiff: ['\frac{\partial {#1}}{\partial {#2}}', 2]
    vc: ['{\mathbf{\boldsymbol{#1}}}', 1]
    qt: ['\hat{\vc {#1}}', 1]
    mt: ['{\mathbf{\boldsymbol{#1}}}', 1]
    pt: ['\boldsymbol{#1}', 1]
    textcolor: ['\color{#1}', 1]

# default settings for whiteboard buttons
whiteboard-active-color: rgb(42,157,223)
whiteboard-background-color: rgb(250,250,250)
whiteboard-icon-size: 2vmin
whiteboard-inactive-color: lightgrey

# Language dictionary. Currently for quiz elements
dictionary:
  de:
    exam:
      Easy: Leicht
      Hard: Schwer
      Medium: Mittelschwer
      again-button: Nochmal
      placeholder: Antwort eingeben
      points: Punkte
      solution: Lösung
      solve-button: Lösen
      reset-button: Zurücksetzen
    quiz:
      solution: Lösung
      reset-button: Zurücksetzen
      input-placeholder: Eingeben und 'Enter'
      qmi-drag-hint: Objekte per Drag&Drop ziehen...
      qmi-drop-hint: ...und hier in die richtige Kategorie einsortieren.
      solve-button: Lösung
  en:
    exam:
      Easy: Easy
      Hard: Hard
      Medium: Medium
      again-button: Again
      placeholder: Type in answer
      points: Points
      solution: Solution
      solve-button: Solve
      reset-button: Reset
    quiz:
      solution: Show Solution
      reset-button: Reset
      input-placeholder: Type and press 'Enter'
      qmi-drag-hint: Drag items from here...
      qmi-drop-hint: ...and put them here into the correct category.
      solution-button: Show Solution
