stages:
  - base
  - deps

image:base:
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: base
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --target base --destination $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:base --verbosity=warn
  rules:
    - changes:
        - Dockerfile
        - .gitlab-ci.yaml
      when: always

image:deps:
  tags:
    - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: deps
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --target deps --destination $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:deps --build-arg IMG_BASE=$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:base --verbosity warn
  rules:
    - changes:
        - Dockerfile
        - stack.yaml
        - package.yaml
        - .gitlab-ci.yaml
      when: always
  needs:
    - job: image:base
      artifacts: false
