FROM ubuntu:bionic
LABEL maintainer="jan-philipp.stauffert@uni-wuerzburg.de"

RUN apt-get update &&	apt-get install -y \
  wget \
  unzip \
  zip \
  libbz2-dev \
  curl \
  gnupg

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && \
  apt-get install -y yarn


#set the encoding on UTF-8, so the parser works correctly, german language is also added for umlaute
#source of fix: https://blog.mkowalski.net/2016/05/16/solving-locale-issues-with-docker-containers/
#RUN apt-get install --reinstall -y locales && \
#        sed -i 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen && \
#        locale-gen de_DE.UTF-8
#ENV LANG de_DE.UTF-8
#ENV LANGUAGE de_DE
#ENV LC_ALL de_DE.UTF-8
#RUN dpkg-reconfigure --frontend noninteractive locales

ENV STACK_ROOT=/root/.stack
RUN mkdir $STACK_ROOT
RUN wget -qO- https://get.haskellstack.org/ | sh

WORKDIR /decker
COPY . /decker
ARG MAKE_FLAGS
RUN stack build --only-dependencies -j8


ENV NODE_PATH=/root/.node_modules
RUN yarn install
RUN cp node_modules /root/.node_modules

RUN rm -rf ./*