FROM ubuntu:bionic
LABEL maintainer="jan-philipp.stauffert@uni-wuerzburg.de"

RUN apt-get update &&	apt-get install -y \
  wget \
  unzip \
  zip \
  libbz2-dev \
  curl \
  gnupg

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && \
  apt-get install -y yarn

ENV STACK_ROOT=/root/.stack
RUN mkdir $STACK_ROOT
RUN wget -qO- https://get.haskellstack.org/ | sh

WORKDIR /decker
COPY . /decker
ARG MAKE_FLAGS
RUN stack build --test -j8 --allow-different-user --fast


ENV NODE_PATH=/root/.node_modules
RUN yarn install
RUN cp -r node_modules /root/.node_modules

RUN rm -rf ./*