name: decker
version: 0.10.0
license: OtherLicense
author: "Henrik Tramberend"
maintainer: "henrik.tramberend@beuth-hochschule.de"
copyright: "2020 Henrik Tramberend"

build-type: Custom

custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - binary
    - bytestring
    - Cabal
    - conduit
    - directory
    - extra
    - filepath
    - Glob
    - zip

extra-source-files:
  - readme.md
  - Dockerfile
  - makefile
  - resource/template/*
  - resource/support/css/*
  - resource/support/js/*
  - resource/example/*
  - third-party/symlinks.mk

synopsis: A markdown based tool for slide deck creation
category: Tool

description: Please see the README at <https://gitlab2.informatik.uni-wuerzburg.de/decker/decker#readme>

dependencies:
  - Glob
  - HTTP
  - aeson
  - ansi-terminal
  - array
  - base >= 4.7 && < 5
  - base16-bytestring
  - base64-bytestring
  - blaze-html
  - blaze-markup
  - bytestring
  - containers
  - data-default
  - directory
  - doctemplates
  - exceptions
  - extra
  - filepath
  - formatting
  - fsnotify
  - groom
  - hashable
  - hspec
  - http-client
  - http-conduit
  - http-types
  - lens
  - lens-action
  - lens-aeson
  - listsafe
  - modern-uri
  - monad-loops
  - mtl
  - multimap
  - mustache
  - neat-interpolation
  - network-uri
  - pandoc
  - pandoc-citeproc
  - pandoc-types
  - process
  - pureMD5
  - random
  - regex-tdfa
  - relude
  - scientific
  - shake
  - snap-core
  - snap-server
  - split
  - tagsoup
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers
  - utf8-string
  - vector
  - websockets
  - websockets-snap
  - wreq
  - xml-conduit
  - xml-types
  - yaml
  - zip

ghc-options:
  - -Wunused-top-binds
  - -Wunused-local-binds
  - -Wincomplete-patterns
  - -fwarn-unused-imports
  # - -Wunused-matches

library:
  source-dirs:
    - src
  when:
    - condition: os(windows)
      then:
        source-dirs: src-win
        exposed-modules: "System.Decker.OS"
      else:
        source-dirs: src-unix
        exposed-modules: "System.Decker.OS"

executables:
  decker:
    main: Decker
    source-dirs: app
    dependencies:
      - decker
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  decker-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - decker

#default-extensions:
  #- DeriveDataTypeable
  #- DeriveGeneric
  #- EmptyCase
  #- FlexibleContexts
  #- FlexibleInstances
  #- GeneralizedNewtypeDeriving
  #- InstanceSigs
  #- LambdaCase
  #- MultiParamTypeClasses
  #- MultiWayIf
  #- NamedFieldPuns
  #- NoMonomorphismRestriction
  #- OverloadedStrings
  #- QuasiQuotes
  #- RecordWildCards
  #- ScopedTypeVariables
  #- TemplateHaskell
  #- TupleSections
