flags:
  regex-posix:
    _regex-posix-clib: true
  pandoc:
    embed_data_files: false
    trypandoc: false
packages:
  - "."
extra-deps:
  - citeproc-0.3.0.5
  - commonmark-0.1.1.3
  - commonmark-extensions-0.2.0.4
  - commonmark-pandoc-0.2.0.1
  - doctemplates-0.9
  - haddock-library-1.9.0
  - hslua-1.3.0
  - HsYAML-aeson-0.2.0.0
  - jira-wiki-markup-1.3.2
  - lens-4.19.2
  - pandoc-2.11.4
  - pandoc-types-1.22
  - regex-posix-clib-2.7
  - rfc5051-0.2
  - skylighting-0.10.2
  - skylighting-core-0.10.2
  - texmath-0.12.1
  - shake-0.19.1
  - pandoc-plot-1.1.1@sha256:5b68c295360a79f973a00f5efc1fc96c04ac7a25055f6576b5abec0d382b76f6,5866
resolver: lts-17.2
ghc-options:
  "$locals": -fhide-source-paths -Wno-missing-home-modules
