ARG IMG_BASE=gitlab2.informatik.uni-wuerzburg.de:4567/decker/decker/master:deps

FROM ${IMG_BASE} as build

WORKDIR /decker
COPY . /decker
ARG MAKE_FLAGS
RUN make ${MAKE_FLAGS} install

RUN ldd /root/.local/bin/decker | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' /root/.local/bin

FROM ubuntu:bionic as decker

RUN apt-get update && apt-get install -y \
    graphviz \
    gnuplot \
    rsync \
    unzip \
    zip

ENV PATH="/root/.local/bin:${PATH}"
COPY --from=build /root/.local /root/.local

#set the encoding on UTF-8, so the parser works correctly, german language is also added for umlaute
#source of fix: https://blog.mkowalski.net/2016/05/16/solving-locale-issues-with-docker-containers/
RUN apt-get install --reinstall -y locales && \
    sed -i 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen de_DE.UTF-8
ENV LANG de_DE.UTF-8
ENV LANGUAGE de_DE
ENV LC_ALL de_DE.UTF-8
RUN dpkg-reconfigure --frontend noninteractive locales

WORKDIR /decker

ENTRYPOINT ["decker"]
