provisioning: Copy
# Sane defaults for reval.js
backgroundTransition: "none"
center: true
controls: true
fragmentInURL: true
fragments: true
hash: true
help: true
hideCursorTime: 2000
hideInactiveCursor: true
history: true
keyboard: true
menu: true
overview: true
progress: true
touch: true
transition: "none"
title: "|title|"
test123: "test123"
align-global: left
             
